Cargo.toml
README.md
src/file_io.rs

Also added a TODO to handle bad paths gracefully in file_io.rs

Update example with correct paths to test files

---

Cargo.lock
Cargo.toml
src/ancestors.rs
src/lib.rs

Created a function `get_intersection_between_sets`(in rust) and corresponding `get_intersection` in PyO3.

Common ancestors

---

Cargo.lock
Cargo.toml
src/lib.rs
src/similarity.rs
src/utils.rs

- Convert a set of strings into integers
- Convert the set back from integers to string

String-to-Integer

---

Cargo.toml
src/lib.rs
src/similarity.rs
src/utils.rs
tests/integration_test.rs

per discussion with @caufieldjh @cmungall @caufieldjh @vinicius at hackathon

Move closure table stuff from OAK to Rustsim

---

Cargo.lock
Cargo.toml

Version bumped

---

.idea/.gitignore
.idea/inspectionProfiles/profiles_settings.xml
.idea/misc.xml
.idea/modules.xml
.idea/rustsim.iml
.idea/vcs.xml
src/lib.rs
src/similarity.rs

rustsim max-ic

---

.github/workflows/qc.yml

Build wheels for 3.11

---

.github/workflows/qc.yml

Added targets:
- aarch64-unknown-linux-gnu
- aarch64-unknown-linux-musl

Add build targets for arm64

---

.github/workflows/qc.yml
Cargo.lock
Cargo.toml
src/lib.rs
src/similarity.rs
src/utils.rs
tests/integration_test.rs

make semsimian struct to hold state

---

Cargo.lock
Cargo.toml
src/utils.rs

Might give the user a better idea of what's going on (probably should be optional, and should emit a message saying what's it's doing)

Add progress bar when building closure and ic map

---

LICENSE

@cmungall @hrshdhgd @caufieldjh @iQuxLE 
to address #52

Add bsd3 license

---

.gitignore
Cargo.lock
src/lib.rs
src/similarity.rs
src/test_utils.rs
src/utils.rs
tests/integration_test.rs

More all X all pairwise similarity calculations

---

python/tests/test_python.py
src/lib.rs
src/utils.rs

Addresses https://github.com/INCATools/ontology-access-kit/issues/596

Accepts threshold values for Jaccard and Resnik Similarity scores

---

src/lib.rs
src/similarity.rs
src/utils.rs

Clippy formatting

---

src/lib.rs
src/utils.rs

Formatting with clippy

---

Cargo.lock
Cargo.toml
src/lib.rs
src/utils.rs

Nothing major just cleaned up some code and made a few efficient tweaks.

Made some efficiency tweaks.

---

Cargo.lock
Cargo.toml
src/lib.rs

This is an additional bug fix needed(continued from #79 )

Columns not sorting caused mismatch in data and headers.

---

.github/workflows/qc.yml
src/utils.rs

Earlier commits for file rename did not work for Windows but worked perfectly for Linux and Mac wheel generations. This PR should fix that and add Windows QC testing too.

Added Windows QC and windows compatible file rename.

---

Cargo.lock
Cargo.toml
benches/termset_pairwise_similarity_benchmark.rs
python/tests/test_python.py
src/lib.rs
src/utils.rs

Added `criterion` crate for benchmarking and possibly profiling.

---

README.md

Add a few sentences up top of README to say exactly what semsimian is

---

.gitignore

A notebook showing the pipeline to inject `monarch-edges.tsv` into `term_association` table of `phenio.db` locally.

Iterate on search

---

tests/test_termset_pairwise_similarity.rs

Added params as passed by the monarch-app.

---

benches/association_search_similarity_benchmark.rs
tests/test_calculate_similarity_for_association_search.rs

Precalculate cache

---

.github/workflows/qc.yml
.github/workflows/release.yml
Cargo.lock
Cargo.toml
README.md

Fixes https://github.com/monarch-initiative/semsimian/issues/120
Duplicate to #121 , #119

Wheel for Python 3.12

---

Cargo.lock
Cargo.toml
build.rs

Based on https://github.com/PyO3/pyo3/blob/main/guide/src/building_and_distribution.md#macos and found by @pkalita-lbl

Adds extra pyo3 build hints

---

Cargo.lock
Cargo.toml
benches/association_flat_search_benchmark.rs
benches/association_full_search_benchmark.rs
benches/association_hybrid_search_benchmark.rs
benches/association_search_similarity_benchmark.rs
python/tests/test_python.py
src/enums.rs
src/lib.rs
src/similarity.rs
tests/integration_test.rs
tests/test_associations_search.rs
tests/test_calculate_similarity_for_association_search.rs

Added unidirection score calculations
